package net.bitflora.asteriskcraft.client;

import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.client.renderer.entity.state.LivingEntityRenderState;

/**
 * Hand-authored geometry for the Photon Cannon: a round disc base filling a 3x3-block footprint
 * (48px across) with a globe hovering above it. Cuboids can't be curved, so every round shape is a
 * bundle of <b>crossed planks</b> — one long box repeated at 0°/45°/90°/135° about the vertical
 * axis. Four planks reaching the same radius cover every direction to that radius, so the union
 * reads as a circle (an inscribed disc that correctly leaves the square's corners empty). The globe
 * is a vertical stack of such plank-rings whose radii follow a sphere profile, capped top and bottom.
 *
 * <p>Each ring is authored as two {@link PartDefinition}s: an axis "plus" (a wide plank + a deep
 * plank) and a 45°-rotated copy of the same, giving the four planks. All disc cubes sample the flat
 * gold zone of {@code textures/entity/photon_cannon.png} and all globe cubes the flat cyan zone
 * (generated by {@code tools/gen_photon_cannon_texture.py}), so cubes freely share texture offsets.
 * Static: the turret doesn't animate; directionality comes from the bolt's beam. Authored in true
 * pixel space (16px = 1 block), so the renderer applies no extra scale.
 */
public class PhotonCannonModel extends EntityModel<LivingEntityRenderState> {
    private static final float DEG45 = 0.7853981633974483f;

    public PhotonCannonModel(ModelPart root) {
        super(root);
    }

    @Override
    public void setupAnim(LivingEntityRenderState state) {
        super.setupAnim(state);
        // no animated parts
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();

        // --- Round disc base, radius 24 (48px = 3 blocks), sitting on the ground (y=24 = feet). ---
        // Four planks (a wide + a deep box, plus a 45°-rotated copy) reaching radius 24 in every
        // direction, so the union is an inscribed circle.
        root.addOrReplaceChild("baseCross",
                CubeListBuilder.create()
                        .texOffs(0, 0).addBox(-24.0f, -4.0f, -10.0f, 48.0f, 4.0f, 20.0f)
                        .texOffs(0, 0).addBox(-10.0f, -4.0f, -24.0f, 20.0f, 4.0f, 48.0f),
                PartPose.offset(0.0f, 24.0f, 0.0f));
        root.addOrReplaceChild("baseCrossDiag",
                CubeListBuilder.create()
                        .texOffs(0, 0).addBox(-24.0f, -4.0f, -10.0f, 48.0f, 4.0f, 20.0f)
                        .texOffs(0, 0).addBox(-10.0f, -4.0f, -24.0f, 20.0f, 4.0f, 48.0f),
                PartPose.offsetAndRotation(0.0f, 24.0f, 0.0f, 0.0f, DEG45, 0.0f));

        // --- Globe hovering above the disc (a ~20px sphere centred ~1.25 blocks up). ---
        // Three plank-rings (radii 10/9/9 following a sphere profile) plus two small square caps.
        // The axis "plus" of every ring lives on "globe"; the 45° copies live on "globeDiag".
        root.addOrReplaceChild("globe",
                CubeListBuilder.create()
                        // mid ring (r=10)
                        .texOffs(0, 60).addBox(-10.0f, -2.0f, -5.0f, 20.0f, 4.0f, 10.0f)
                        .texOffs(0, 60).addBox(-5.0f, -2.0f, -10.0f, 10.0f, 4.0f, 20.0f)
                        // upper ring (r=9)
                        .texOffs(0, 60).addBox(-9.0f, -6.0f, -4.5f, 18.0f, 4.0f, 9.0f)
                        .texOffs(0, 60).addBox(-4.5f, -6.0f, -9.0f, 9.0f, 4.0f, 18.0f)
                        // lower ring (r=9)
                        .texOffs(0, 60).addBox(-9.0f, 2.0f, -4.5f, 18.0f, 4.0f, 9.0f)
                        .texOffs(0, 60).addBox(-4.5f, 2.0f, -9.0f, 9.0f, 4.0f, 18.0f)
                        // caps
                        .texOffs(0, 60).addBox(-6.0f, -10.0f, -6.0f, 12.0f, 4.0f, 12.0f)
                        .texOffs(0, 60).addBox(-6.0f, 6.0f, -6.0f, 12.0f, 4.0f, 12.0f),
                PartPose.offset(0.0f, 4.0f, 0.0f));
        root.addOrReplaceChild("globeDiag",
                CubeListBuilder.create()
                        .texOffs(0, 60).addBox(-10.0f, -2.0f, -5.0f, 20.0f, 4.0f, 10.0f)
                        .texOffs(0, 60).addBox(-5.0f, -2.0f, -10.0f, 10.0f, 4.0f, 20.0f)
                        .texOffs(0, 60).addBox(-9.0f, -6.0f, -4.5f, 18.0f, 4.0f, 9.0f)
                        .texOffs(0, 60).addBox(-4.5f, -6.0f, -9.0f, 9.0f, 4.0f, 18.0f)
                        .texOffs(0, 60).addBox(-9.0f, 2.0f, -4.5f, 18.0f, 4.0f, 9.0f)
                        .texOffs(0, 60).addBox(-4.5f, 2.0f, -9.0f, 9.0f, 4.0f, 18.0f),
                PartPose.offsetAndRotation(0.0f, 4.0f, 0.0f, 0.0f, DEG45, 0.0f));

        return LayerDefinition.create(mesh, 256, 256);
    }
}
